server:
  port: 8050
  shutdown: graceful

spring:
  application:
    name: rating
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ratings}
    username: ${SPRING_DATASOURCE_USERNAME:program}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://dev-1qtseeouvdob2c1k.us.auth0.com/}
          jwk-set-uri: ${JWT_JWK_SET_URI:https://dev-1qtseeouvdob2c1k.us.auth0.com/.well-known/jwks.json}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true