auth:
  username: postgres
  password: postgres
  database: postgres
  postgresPassword: postgres
primary:
  persistence:
    enabled: false
  initdb:
    scripts:
      db-v4.sql: |
        CREATE USER program WITH PASSWORD 'test';
        CREATE DATABASE reservations;
        CREATE DATABASE libraries;
        CREATE DATABASE ratings;
        GRANT ALL PRIVILEGES ON DATABASE reservations TO program;
        GRANT ALL PRIVILEGES ON DATABASE libraries   TO program;
        GRANT ALL PRIVILEGES ON DATABASE ratings     TO program;