replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /
  pathType: Prefix
  annotations: {}

env: []
  # - name: SPRING_DATASOURCE_URL
#   value: jdbc:postgresql://postgres-postgresql.rsoi.svc.cluster.local:5432/ratings

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 40
  periodSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 5

podAnnotations: {}
podLabels: {}

nodeSelector: {}
tolerations: []
affinity: {}